--1
SELECT EMPLOYEE_ID, LAST_NAME, SALARY*12 "ANNUAL SALLARY"
FROM EMPLOYEES;

--2
SELECT * 
FROM DEPARTMENTS;

--3
SELECT EMPLOYEE_ID, FIRST_NAME|| ' ' || LAST_NAME "NAME", JOB_ID, HIRE_DATE
 "STARTDATE"
FROM EMPLOYEES;

--4
SELECT FIRST_NAME|| ' ' || LAST_NAME || ', ' || JOB_ID "Employee and Title"
FROM EMPLOYEES;